const appName = "Finey";
export const splashPhrases = [
  "Pessoas que acompanham seus gastos economizam em média 20% mais por mês.",
  "Usuários de apps de gestão financeira têm 3x mais chances de atingir suas metas de economia.",
  "Apenas 30% dos brasileiros fazem um controle efetivo de suas finanças pessoais.",
  "Quem planeja suas finanças tem 70% mais chances de realizar seus sonhos de consumo.",
  "Economizar 10% da sua renda mensal pode gerar um patrimônio de mais de R$100 mil em 10 anos.",
  "Pessoas que usam apps de gestão financeira reduzem suas dívidas 35% mais rápido.",
  "Investir R$100 por mês com juros compostos de 10% ao ano gera R$41.000 em 15 anos.",
  "Famílias que fazem orçamento doméstico têm 21% menos estresse financeiro.",
  "Apenas 12% dos brasileiros conseguem manter uma reserva de emergência adequada.",
  "Quem monitora seus gastos diariamente economiza até 15% mais que a média.",
  "Pessoas organizadas financeiramente têm 44% menos chances de ter problemas com dívidas.",
  "Investir 15% do seu salário desde os 25 anos pode garantir sua aposentadoria aos 60.",
  "Brasileiros gastam em média 30% da renda com despesas desnecessárias que poderiam ser economizadas.",
  "Quem usa categorias para organizar gastos identifica até 25% de despesas que podem ser reduzidas.",
  "Apenas 8% dos brasileiros conseguem manter um controle financeiro por mais de 6 meses consecutivos.",
  "Pessoas que definem metas financeiras claras têm 42% mais chances de alcançá-las.",
  "Famílias que fazem planejamento financeiro têm 78% menos chances de enfrentar dificuldades em emergências.",
  "Quem poupa regularmente tem 3x menos ansiedade relacionada a dinheiro.",
  "Usuários de aplicativos financeiros conseguem reduzir gastos supérfluos em até 30%.",
  "Apenas 25% dos brasileiros sabem exatamente quanto gastam com alimentação por mês.",
  "Pessoas que revisam suas finanças semanalmente economizam 2x mais que aquelas que fazem mensalmente.",
  "Quem automatiza suas economias consegue poupar 63% mais que quem faz manualmente.",
  "Brasileiros com educação financeira têm 76% menos chances de entrar no cheque especial.",
  "Famílias que discutem abertamente sobre finanças têm 45% menos conflitos relacionados a dinheiro.",
  "Pessoas que controlam pequenos gastos diários podem economizar até R$500 por mês sem perceber.",
  "Quem investe regularmente tem patrimônio 4x maior após 10 anos comparado a quem só poupa.",
  "Apenas 5% dos brasileiros conseguem se aposentar com conforto financeiro.",
  "Usuários de gestão financeira identificam em média 18% de gastos desnecessários em suas contas.",
  "Pessoas que pagam à vista economizam em média 15% em suas compras.",
  "Quem monitora seus investimentos mensalmente obtém rendimentos 22% maiores.",
  "Brasileiros que usam apps financeiros têm 58% mais chances de sair das dívidas em um ano.",
  "Famílias com orçamento definido têm 3x menos chances de precisar de empréstimos emergenciais.",
  "Pessoas que definem limites de gastos por categoria economizam 31% mais que a média.",
  "Apenas 15% dos brasileiros sabem exatamente quanto pagam de juros em suas dívidas.",
  "Quem poupa primeiro e gasta depois acumula 2,5x mais patrimônio em 20 anos.",
  "Usuários de gestão financeira têm 67% menos chances de atrasar pagamentos de contas.",
  "Pessoas que fazem compras planejadas gastam 23% menos que compradores impulsivos.",
  "Brasileiros que controlam suas finanças têm 40% menos estresse no dia a dia.",
  "Quem diversifica investimentos tem 35% menos risco de perder patrimônio em crises.",
  "Apenas 7% dos brasileiros conseguem manter um controle efetivo de pequenos gastos diários.",
  "Pessoas que definem metas financeiras específicas poupam 3x mais que aquelas com metas vagas.",
  "Famílias que ensinam educação financeira aos filhos têm 65% menos problemas com dívidas futuras.",
  "Quem revisa seus gastos fixos anualmente economiza em média R$2.400 por ano.",
  "Brasileiros que usam gestão financeira têm 52% mais chances de realizar sonhos como viagens.",
  "Pessoas que controlam impulsos de compra economizam até 40% em itens não essenciais.",
  "Apenas 10% dos brasileiros conseguem manter um fluxo de caixa pessoal organizado.",
  "Quem poupa com objetivos específicos tem 73% mais motivação para continuar economizando.",
  "Usuários de apps financeiros identificam em média 12 assinaturas esquecidas por ano.",
  "Pessoas que fazem análises mensais de gastos reduzem despesas em 18% no primeiro ano.",
  "Brasileiros organizados financeiramente têm 3x mais chances de conquistar independência financeira.",
  "Quem separa dinheiro para diferentes objetivos tem 81% mais chances de realizá-los.",
  "Apenas 20% dos brasileiros conseguem manter suas economias intactas por mais de um ano.",
  "Pessoas que automatizam pagamentos economizam em média 10 horas por mês em gestão financeira.",
  "Famílias que fazem compras com lista economizam até 23% no supermercado.",
  "Quem monitora seu score de crédito regularmente consegue taxas de juros 30% menores.",
  "Brasileiros que usam gestão financeira têm 47% menos chances de precisar de empréstimos.",
  "Pessoas que investem regularmente desde jovens podem se aposentar até 10 anos antes.",
  "Apenas 3% dos brasileiros conseguem manter um controle detalhado de todos seus investimentos.",
  "Quem planeja grandes compras com antecedência economiza em média 27% no valor final.",
  "Usuários de apps financeiros têm 62% mais chances de identificar cobranças indevidas.",
  "Pessoas que fazem revisão semanal de gastos têm 39% menos chances de estourar o orçamento.",
  "Brasileiros que controlam finanças têm 50% mais chances de realizar o sonho da casa própria.",
  "Quem mantém reserva de emergência tem 85% menos estresse em momentos de crise financeira.",
  "Apenas 18% dos brasileiros sabem exatamente quanto precisam para se aposentar confortavelmente.",
  "Pessoas que definem orçamentos realistas têm 3x mais sucesso em cumpri-los.",
  "Famílias que fazem planejamento tributário economizam em média 15% em impostos anualmente.",
  "Quem acompanha tendências de mercado tem 41% mais retorno em seus investimentos.",
  "Brasileiros que usam gestão financeira têm 73% mais chances de realizar objetivos de longo prazo.",
  "Pessoas que controlam pequenos vazamentos financeiros acumulam 25% mais patrimônio em 5 anos.",
  "Apenas 6% dos brasileiros conseguem equilibrar perfeitamente gastos, poupança e investimentos.",
  "Quem renegocia dívidas com planejamento consegue economizar até 40% no valor total.",
  "Usuários de apps financeiros identificam padrões de gastos que podem ser otimizados em 22%.",
  "Pessoas que fazem planejamento financeiro têm 57% menos chances de precisar de empréstimos emergenciais.",
  "Brasileiros que controlam finanças têm qualidade de vida 35% superior em pesquisas de bem-estar.",
  "Quem investe com estratégia definida tem rendimentos 3x maiores que investidores ocasionais.",
  "Apenas 9% dos brasileiros conseguem manter um equilíbrio saudável entre poupar e aproveitar a vida.",
  "Pessoas que definem limites claros para categorias de gastos economizam 29% mais que a média.",
  "Famílias que ensinam finanças aos filhos desde cedo têm 70% menos problemas financeiros intergeracionais.",
  "Quem monitora taxas bancárias economiza em média R$850 por ano em tarifas desnecessárias.",
  "Brasileiros que usam gestão financeira têm 61% mais chances de realizar sonhos como empreender.",
  "Pessoas que controlam impulsos de compra têm 3x mais satisfação com suas aquisições.",
  "Apenas 14% dos brasileiros conseguem manter um controle efetivo de gastos em viagens.",
  "Quem poupa com metas específicas tem 2,7x mais chances de atingir o valor necessário no prazo.",
  "Usuários de apps financeiros conseguem identificar em média 15% de oportunidades de economia em contas fixas.",
  "Pessoas que fazem revisão trimestral de seguros e serviços economizam até R$3.600 por ano.",
  "Brasileiros organizados financeiramente têm 48% menos problemas de saúde relacionados ao estresse.",
  "Quem diversifica fontes de renda tem 75% mais segurança financeira em momentos de crise.",
  "Apenas 4% dos brasileiros conseguem manter um controle efetivo de gastos com cartão de crédito.",
  "Pessoas que automatizam investimentos acumulam 2,3x mais patrimônio em 15 anos.",
  "Famílias que fazem planejamento de compras sazonais economizam até 35% anualmente.",
  "Quem monitora seu patrimônio líquido mensalmente tem 53% mais motivação para economizar.",
  "Brasileiros que usam gestão financeira têm 69% mais chances de realizar o sonho de estudar fora.",
  "Pessoas que controlam gastos emocionais economizam em média 27% de sua renda disponível.",
  "Apenas 11% dos brasileiros conseguem manter um fluxo de caixa positivo por mais de 5 anos consecutivos.",
  "Quem planeja a aposentadoria desde cedo tem 4x mais chances de se aposentar com conforto.",
  "Usuários de apps financeiros têm 55% menos chances de cair em golpes financeiros.",
  "Pessoas que fazem análise mensal de extratos bancários identificam em média 8% de gastos desnecessários.",
  "Brasileiros que controlam finanças têm 43% mais chances de realizar o sonho de ter filhos com segurança financeira.",
  "Quem mantém um fundo para oportunidades consegue aproveitar investimentos com 31% mais retorno.",
  "Apenas 16% dos brasileiros conseguem manter uma proporção saudável entre dívidas e renda.",
  "Pessoas que definem prioridades financeiras claras têm 2,5x mais satisfação com suas escolhas de vida.",
  "Famílias que fazem planejamento sucessório economizam até 40% em impostos sobre herança.",
  "Quem acompanha indicadores econômicos regularmente toma decisões financeiras 27% mais acertadas.",
  "Brasileiros que usam gestão financeira têm 59% mais chances de mudar de carreira com segurança.",
  "Pessoas que controlam compras por impulso têm 3,2x mais dinheiro disponível para investimentos.",
  "Apenas 8% dos brasileiros conseguem manter um controle efetivo de gastos com alimentação fora de casa.",
  "Quem poupa com propósito tem 67% mais motivação para superar dificuldades financeiras.",
  "Usuários de apps financeiros conseguem reduzir o tempo de pagamento de dívidas em 40%.",
  "Pessoas que fazem planejamento financeiro familiar têm 51% menos conflitos relacionados a dinheiro.",
  "Brasileiros que controlam finanças têm 38% mais chances de realizar o sonho de abrir um negócio.",
  "Quem investe em conhecimento financeiro tem retorno médio 22% maior em seus investimentos.",
  "Apenas 7% dos brasileiros conseguem manter um equilíbrio ideal entre curto, médio e longo prazo nas finanças.",
  "Pessoas que definem metas financeiras SMART têm 3,5x mais chances de alcançá-las no prazo.",
  "Famílias que fazem planejamento de gastos sazonais economizam até 28% em datas comemorativas.",
  "Quem monitora a relação renda/despesa mensalmente tem 45% menos chances de entrar no vermelho.",
  "Brasileiros que usam gestão financeira têm 71% mais chances de realizar o sonho de ter um hobby sem culpa.",
  "Pessoas que controlam gastos supérfluos conseguem investir em média 23% mais de sua renda.",
  "Apenas 13% dos brasileiros conseguem manter um controle efetivo de gastos com lazer e entretenimento.",
  "Quem poupa com estratégia definida tem 2,9x mais patrimônio após 10 anos que poupadores ocasionais.",
  "Usuários de apps financeiros identificam em média 14 oportunidades de economia por mês.",
  "Pessoas que fazem revisão anual de planos de saúde e seguros economizam até R$2.700 por ano.",
  "Brasileiros organizados financeiramente têm 42% mais tempo livre por não precisarem de trabalhos extras.",
  "Quem diversifica investimentos conforme objetivos tem 37% mais chances de realizar todos seus sonhos.",
  "Apenas 5% dos brasileiros conseguem manter um controle efetivo de pequenos gastos recorrentes.",
  "Pessoas que automatizam pagamentos e investimentos economizam em média 8 horas por mês em gestão financeira.",
  "Famílias que fazem planejamento de compras grandes economizam até 32% no valor final.",
  "Quem monitora seu orçamento semanalmente tem 49% menos chances de precisar de empréstimos.",
  "Brasileiros que usam gestão financeira têm 63% mais chances de realizar o sonho de ajudar financeiramente os pais.",
  "Pessoas que controlam gastos emocionais têm 3,7x mais satisfação com suas decisões financeiras.",
  "Apenas 9% dos brasileiros conseguem manter um controle efetivo de gastos com presentes e doações.",
  "Quem planeja a educação dos filhos desde o nascimento economiza até 45% no custo total.",
  "Usuários de apps financeiros têm 57% mais clareza sobre para onde vai seu dinheiro.",
  "Pessoas que fazem análise trimestral de gastos fixos reduzem essas despesas em média 12% ao ano.",
  "Brasileiros que controlam finanças têm 41% mais chances de realizar o sonho de fazer uma viagem internacional.",
  "Quem mantém reservas específicas para diferentes objetivos tem 83% mais chances de realizá-los no prazo.",
  "Apenas 6% dos brasileiros conseguem manter um equilíbrio saudável entre trabalho, lazer e poupança.",
  "Pessoas que definem regras claras para uso do cartão de crédito economizam 34% em juros e tarifas.",
  "Famílias que fazem planejamento financeiro conjunto têm 47% menos discussões sobre dinheiro.",
  "Quem acompanha seus investimentos regularmente obtém rendimentos 25% maiores no longo prazo.",
  "Brasileiros que usam gestão financeira têm 68% mais chances de realizar o sonho de ter um carro sem comprometer o orçamento.",
  "Pessoas que controlam gastos por categorias identificam em média 19% de oportunidades de economia.",
  "Apenas 12% dos brasileiros conseguem manter um controle efetivo de gastos com assinaturas digitais.",
  "Quem poupa com objetivos claros tem 3,1x mais motivação para resistir a tentações de consumo.",
  "Usuários de apps financeiros conseguem reduzir gastos com juros em média 42% ao ano.",
  "Pessoas que fazem planejamento tributário familiar economizam até 17% em impostos anualmente.",
  "Brasileiros organizados financeiramente têm 39% mais segurança para tomar decisões de carreira.",
  "Quem investe regularmente desde o primeiro salário pode se aposentar com o dobro do patrimônio.",
  "Apenas 10% dos brasileiros conseguem manter um controle efetivo de gastos com manutenção de bens.",
  "Pessoas que automatizam suas finanças têm 2,2x mais tempo para focar em aumentar a renda.",
  "Famílias que fazem planejamento de compras mensais economizam até 25% no supermercado.",
  "Quem monitora seu patrimônio trimestralmente tem 51% mais motivação para continuar investindo.",
  "Brasileiros que usam gestão financeira têm 72% mais chances de realizar o sonho de fazer uma transição de carreira.",
  "Pessoas que controlam pequenos gastos diários acumulam em média R$7.200 a mais por ano.",
  "Apenas 8% dos brasileiros conseguem manter um controle efetivo de gastos com datas comemorativas.",
  "Quem planeja grandes compras com 6 meses de antecedência economiza em média 33% no valor final.",
  "Usuários de apps financeiros têm 59% menos estresse relacionado a contas e prazos de pagamento.",
  "Pessoas que fazem revisão mensal de gastos variáveis reduzem essas despesas em média 15% ao ano.",
  "Brasileiros que controlam finanças têm 45% mais chances de realizar o sonho de fazer uma pós-graduação.",
  "Quem mantém múltiplas reservas de emergência tem 91% menos ansiedade financeira em crises.",
  "Apenas 11% dos brasileiros conseguem manter um equilíbrio saudável entre consumo presente e poupança futura.",
  "Pessoas que definem limites de gastos por aplicativo têm 3,3x mais controle sobre compras digitais.",
  "Famílias que fazem planejamento financeiro de férias economizam até 37% no custo total.",
  "Quem acompanha relatórios financeiros mensais identifica padrões que geram 21% de economia.",
  "Brasileiros que usam gestão financeira têm 64% mais chances de realizar o sonho de ter uma aposentadoria tranquila.",
  "Pessoas que controlam gastos impulsivos conseguem investir em média 28% mais de sua renda mensal.",
  "Apenas 7% dos brasileiros conseguem manter um controle efetivo de gastos com tecnologia e eletrônicos.",
  "Quem poupa com metas visuais tem 2,8x mais persistência em momentos de dificuldade financeira.",
  "Usuários de apps financeiros identificam em média 9 oportunidades de investimento melhores por ano.",
  "Pessoas que fazem planejamento financeiro familiar têm 53% menos preocupações com o futuro.",
  "Brasileiros organizados financeiramente têm 44% mais liberdade para escolher trabalhos que realmente gostam.",
  "Quem diversifica investimentos conforme perfil de risco tem 33% mais retorno ajustado ao risco.",
  "Apenas 9% dos brasileiros conseguem manter um controle efetivo de gastos com vestuário e acessórios.",
  "Pessoas que automatizam decisões financeiras têm 2,4x menos arrependimentos de compra.",
  "Famílias que fazem planejamento de gastos educacionais economizam até 29% no custo total da formação dos filhos.",
  "Quem monitora seu orçamento diariamente tem 47% menos chances de fazer compras por impulso.",
  "Brasileiros que usam gestão financeira têm 66% mais chances de realizar o sonho de ter uma casa de praia ou campo.",
  "Pessoas que controlam gastos emocionais têm patrimônio 3,5x maior após 10 anos.",
  "Apenas 10% dos brasileiros conseguem manter um controle efetivo de gastos com hobbies e lazer.",
  "Quem planeja a aposentadoria com estratégia definida consegue se aposentar em média 7 anos antes.",
  "Usuários de apps financeiros têm 61% mais clareza sobre seus verdadeiros objetivos financeiros.",
  "Pessoas que fazem análise semestral de seguros e serviços economizam até R$4.200 por ano.",
  "Brasileiros que controlam finanças têm 49% mais chances de realizar o sonho de fazer uma grande celebração sem dívidas."
]